### ISSUE TITLE
Adapt subcrate tls-client to inherit workspace dependencies

### ISSUE THREAD

**Issue by th4s** [tlsnotary/tlsn#103]
PR #102 introduced inheritance of workspace dependencies. The sub-crate `tls-client` currently cannot do this, because it is excluded from the workspace at the moment.

Once it is no longer [excluded](https://github.com/tlsnotary/tlsn/blob/dev/Cargo.toml#L14), adapt it, to also inherit workspace dependencies.

**Comment by heeckhau** [comment]
@th4s can you check this issue? It looks like this is already fixed.
