### ISSUE TITLE
Simplified 2PC point addition

### ISSUE THREAD

**Issue by themighty1** [tlsnotary/tlsn#107]
The current point_addition protocol can be greatly simplified.

We will use the `M2A` and `A2M` protocols from https://www.cs.umd.edu/~fenghao/paper/modexp.pdf (p. 25)

From the original write-up (https://tlsnotary.org/how_it_works#section1) we want to compute in 2PC the additive shares of $(\frac{y_q-y_p}{x_q-x_p})^2 - x_p - x_q$

For clarity, expanding the above into 3 terms `A*B+C` :

$(y_q^2 - 2y_qy_p + y_p^2) * (\frac{1}{x_q^2 - 2x_qx_p + x_p^2}) + (- x_p - x_q)$

Term A: 
- compute additive shares of $2y_qy_p$ using `M2A`, then each party respectively adds $y_q^2$ and $y_p^2$ to their additive share. The result is additive shares $A_p$ and $A_q$

Term B: 
- compute additive shares of $2x_qx_p$ using `M2A`, then each party respectively adds $x_q^2$ and $x_p^2$ to their additive share. The result is $\frac{1}{D_p + D_q}$.

- compute multiplicative shares of $D_p + D_q$ using `A2M`, the result is $(\frac{1}{M_p}) * (\frac{1}{M_q})$.

- each party locally computes an inverse of their share `M` and calls it `MInv` 

- compute additive shares of $MInv_p * MInv_q$ using `M2A`. The result is additive shares $B_p$ and $B_q$

Term A * B:

Given that $(A_p + A_q)*(B_p + B_q) = A_pB_p + A_pB_q + A_qB_p + A_qB_q$, the 1st and the 4th terms each party computes locally but the 2nd and the 3rd terms are computed using `M2A`. The result is additive shares $AB_p$ and $AB_q$

Term C:

Finally, the respective party locally subtracts $AB_p - x_p$ and $AB_q - x_q$ and arrives at their point addition shares.

**Comment by th4s** [comment]
Ack, makes sense for me.

**Comment by themighty1** [comment]
We can decrease the number of communication rounds from 3 to 2 in this way.


From the original write-up (https://tlsnotary.org/how_it_works#section1) we want to compute in 2PC:
$(\frac{y_q-y_p}{x_q-x_p})^2 - x_p - x_q$


Round 1:

Using `A2M`, the parties first convert $y_q-y_p$ and then convert $x_q-x_p$ into multiplicative shares $A * B$ and $C * D$, respectively, which leads us to 

$(\frac{A}{B})^2 * (\frac{C}{D})^2 - x_p - x_q$

The parties then square their respective terms and convert the fractions (mod p) into integers (mod p) which leads to

$E * F - x_p - x_q$

Round 2:

The parties use `M2A` to convert $E * F$ into additive shares.

**Comment by valpaq** [comment]
Hi, is it still active issue? if no one already working on it, I wanna help, however will ask clarification questions, okay?

**Comment by themighty1** [comment]
thank you. closing since that PR implemented it.
