### ISSUE TITLE
add tests for Circuit validation

### ISSUE THREAD

**Issue by themighty1** [tlsnotary/tlsn#158]
Our circuit builder tool may be used by other projects at some point. We want to have proper tests for circuit validation methods
https://github.com/tlsnotary/tlsn/blob/ee45cb4bd92648038084d84c90530ed31f758af1/mpc/mpc-circuits/src/circuit.rs#L259

**Comment by valpaq** [comment]
have some questions https://github.com/tlsnotary/tlsn/pull/164, pls help

**Comment by valpaq** [comment]
@sinui0 if I understand correctly, issue is solved? can close?

**Comment by themighty1** [comment]
yes, thanks.
