### ISSUE TITLE
Intermediate Wire Groups

### ISSUE THREAD

**Issue by sinui0** [tlsnotary/tlsn#185]
We need support for specifying "intermediate" wire groups. These are groups of wires which are not in the input or output layers of a circuit.

This feature will be helpful for chaining circuits together. For example, we may want to re-use labels for a value in a circuit which isn't present in the output. #199 is a good example of where this feature would remove a ton of verbosity. Currently we have to derive the key stream labels by manually XORing some labels together, rather than just accessing them directly like `gc.get_int_labels()[keystream.idx()]`

**Comment by valpaq** [comment]
what do mean support? new field in the structure? or add their verification?
