### ISSUE TITLE
About Rust Edition

### ISSUE THREAD

**Issue by marvellous987** [tlsnotary/tlsn#26]
Hi,

When I try to run the example in ```mpc-core/examples/garble.rs```, I encountered an error about the "edition":

```
$ cargo run --example garble

error: failed to parse manifest at `/Users/xxx/Desktop/tlsn-master/mpc-aio/Cargo.toml`

Caused by:
  failed to parse the `edition` key

Caused by:
  this version of Cargo is older than the `2021` edition, and only supports `2015` and `2018` editions.
```

I tried ```cargo fix --edition``` but it does not work.

Would anyone give me some help about this?

Thank you!

**Comment by themighty1** [comment]
Hi, please try to use the nightly version of rust with

`rustup default nightly`

**Comment by marvellous987** [comment]
Hi, thanks for the reply. I am sorry that I did not mention my rust version. My rust version is ```rustc 1.62.0-nightly (52ca603da 2022-04-12)```. 

I also tried ```rustup default nightly``` but the problem still....

**Comment by themighty1** [comment]
It worked for me on   stable-x86_64-unknown-linux-gnu unchanged - rustc 1.59.0 (9d1b2106e 2022-02-23)
I had to cd mpc-core/examples and then cargo run --example garble

**Comment by marvellous987** [comment]
Thanks! The problem is solved!
