### ISSUE TITLE
Support deferred decryption

### ISSUE THREAD

**Issue by sinui0** [tlsnotary/tlsn#330]
Support deferring decryption of server response data until *after the TLS connection is closed*. Once the connection is closed, the Verifier can reveal their share of the TLS session keys to the Prover. The Prover can then decrypt the payload without using full MPC, but rather just the ZK phase of DEAP. This is a significant optimization to total protocol time as it eliminates the majority of the *upload bandwidth* constraint.

**Comment by ameya-deshmukh** [comment]
@sinui0 can I take this up?

**Comment by ameya-deshmukh** [comment]
Sure, will do!
