### ISSUE TITLE
Optimize matrix transposition function

### ISSUE THREAD

**Issue by sinui0** [tlsnotary/tlsn#4]
Our current matrix transposition function, used during OT extension, is naively implemented to first transform the matrix into boolean vectors. This is not efficient and is a good target for optimization.

```rust
pub fn transpose(m: &Vec<Vec<u8>>) -> Vec<Vec<u8>> {
    let bits: Vec<Vec<bool>> = m.iter().map(|row| u8vec_to_boolvec(row)).collect();
    let col_count = bits[0].len();
    let row_count = bits.len();

    let mut bits_: Vec<Vec<bool>> = vec![vec![false; row_count]; col_count];
    let mut m_: Vec<Vec<u8>> = Vec::with_capacity(col_count);

    for j in 0..row_count {
        for i in 0..col_count {
            bits_[i][j] = bits[j][i];
        }
    }

    for row in bits_.iter() {
        m_.push(boolvec_to_u8vec(row));
    }

    m_
}
```

**Comment by themighty1** [comment]
@th4s, since we are primarily concerned with performance in wasm, one would have to make sure that _mm256_movemask_epi8 compiles to wasm or find a substitute for that intrinsic.

**Comment by th4s** [comment]
I played around a little bit and it seems that there is a 128bit version of this function available in WASM.

See:
- https://nickb.dev/blog/authoring-a-simd-enhanced-wasm-library-with-rust/
- https://doc.rust-lang.org/beta/core/arch/wasm32/fn.u8x16_bitmask.html

I just pushed a branch, which is WIP: https://github.com/tlsnotary/tlsn/tree/matrix-transpose

**Comment by themighty1** [comment]
> I played around a little bit and it seems that there is a 128bit version of this function available in WASM.

This should work by calling the 128-bit version on the low 128 bits and then on the high 128 bits.

**Comment by themighty1** [comment]
There a matrix transpose impl here https://gitlab.com/neucrypt/mpecdsa/-/blob/release/src/ote.rs
havent dug into it, it may or may not be faster
