### ISSUE TITLE
Document how to filter notary server logs

### ISSUE THREAD

**Issue by sinui0** [tlsnotary/tlsn#412]
We should document how to filter notary server logs to only `tlsn` crates.

The notary server uses [`EnvFilter`](https://docs.rs/tracing-subscriber/latest/tracing_subscriber/filter/struct.EnvFilter.html) and can be configured using `RUST_LOG`. We should document how to use it.

**Comment by heeckhau** [comment]
@yuroitaki can I assign this to you?
