### ISSUE TITLE
Render notary server openapi spec visually on doc webpage

### ISSUE THREAD

**Issue by yuroitaki** [tlsnotary/tlsn#442]
Instead of linking to the spec file (https://docs.tlsnotary.org/developers/notary_server.html#api-endpoints), we should render the spec visually (like https://editor.swagger.io/) in the same page embedded or a separate page.

Ref: https://swagger.io/docs/open-source-tools/swagger-ui/development/setting-up/

**Comment by waddaboo** [comment]
Hi, I would like to take on this issue :)

**Comment by yuroitaki** [comment]
> Hi, I would like to take on this issue :)

Go ahead! Let us know if you have any question :)

**Comment by waddaboo** [comment]
How would you like this to be implemented? Based on my understanding we can:
1. Do it like how it's done in [tlsnotary/docs-mdbook](https://github.com/tlsnotary/docs-mdbook/blob/main/src/developers/notary_server.md)
2. Host it with [SwaggerHub](https://swagger.io/tools/swaggerhub/)'s Cloud Hosting
3. Host the generated dist files at the place of your choosing. Reference: [here](https://github.com/swagger-api/swagger-ui/blob/HEAD/docs/usage/installation.md)

**Comment by waddaboo** [comment]
Able to achieve similar result for option 3 by pushing the html file to repo and use [htmlpreview](https://github.com/htmlpreview/htmlpreview.github.com) to load the swagger page. 

Should this html file be pushed to this repo or the doc website repo?

**Comment by yuroitaki** [comment]
> Able to achieve similar result for option 3 by pushing the html file to repo and use [htmlpreview](https://github.com/htmlpreview/htmlpreview.github.com) to load the swagger page.
> 
> Should this html file be pushed to this repo or the doc website repo?
> 
> Edit: I noticed the doc website repo is on GitHub pages. It should be able to display the Swagger html file without needing to use htmlpreview.

nice! the swagger ui html file should be in the doc website repo yes, sorry this issue should have been filed in that repo instead haha.

**Comment by waddaboo** [comment]
Noted, thanks! I'll make a pr request there.

**Comment by yuroitaki** [comment]
Completed in https://github.com/tlsnotary/docs-mdbook/pull/79
