### ISSUE TITLE
Update all hyper dependencies

### ISSUE THREAD

**Issue by heeckhau** [tlsnotary/tlsn#445]
The examples were recently updated to use `hyper` 1.1.

In other places we still use older versions:
* https://github.com/tlsnotary/tlsn/blob/dev/tlsn/Cargo.toml#L43
* https://github.com/tlsnotary/tlsn/blob/dev/notary-server/Cargo.toml#L19
* https://github.com/tlsnotary/tlsn/blob/dev/components/tls/Cargo.toml#L37

I propose we update them all to the latest version

**Comment by yuroitaki** [comment]
Closing this as it's completed in https://github.com/tlsnotary/tlsn/pull/480
