### ISSUE TITLE
Add memory profiling to benchmarks

### ISSUE THREAD

**Issue by sinui0** [tlsnotary/tlsn#462]

**Comment by valo** [comment]
I believe I can contribute in this. We can use `valgrind DHAT` tool to profile the memory. Here is the output of running `valgrind --tool=dhat ./target/release/examples/interactive`:

```
==110432== Total:     5,142,194,819 bytes in 6,534,290 blocks
==110432== At t-gmax: 515,650,506 bytes in 69,816 blocks
==110432== At t-end:  214,519,160 bytes in 235 blocks
==110432== Reads:     12,516,152,734 bytes
==110432== Writes:    8,497,412,743 bytes
```

It takes 2 minutes to run the `interactive` example through this tool, so it adds quite a bit of execution overhead. Given that I think the memory profiling should be an option flag.

Do you think that will be useful? Should I add this as a flag in the `benches` crate? May be even parse the total counters and add it to the `metrics.csv`?

Here is the detail profile in a DHAT viewer:

![image](https://github.com/user-attachments/assets/a1d27115-bcba-41ef-8398-8268759e58cb)
