### ISSUE TITLE
Documentation/Insights on how a response from a Websocket client can be Notarised.

### ISSUE THREAD

**Issue by xomexh** [tlsnotary/tlsn#487]
Many thanks for the work on this, it's a great project which is helping me better my understanding of data provenance projects. 

Is there available any documentation about how I can setup the Notary in such a way, that my client receives data from a Websocket stream, and then the Notary can _notarize_ it. 

The examples of simple and interactive were of good help to bring me upto pace to how Notary can be used to Notarize HTTPS API requests. Any such documentation or insights on how to handle Web-socket streams would be greatly helpful.

Best Regards!

**Comment by yuroitaki** [comment]
Hey I am afraid all our examples/documentations are catered for HTTP API requests, though one should be able to change that to WebSocket API by changing this [chunk](https://github.com/tlsnotary/tlsn/blob/main/tlsn/examples/discord/discord_dm.rs#L69-L107) from e.g. the discord example , which essentially attaches `tls_connection` returned from the [prover library](https://github.com/tlsnotary/tlsn/blob/main/tlsn/examples/discord/discord_dm.rs#L64) to an application layer protocol, e.g. HTTP or WebSocket. Something like [async_tungstenite](https://docs.rs/async-tungstenite/latest/async_tungstenite/struct.WebSocketStream.html#method.from_raw_socket) should help with that setup and subsequent communication with the data server via WebSocket to request for the data you want to notarize.

Feel free to drop by our [discord](https://discord.com/invite/9XwESXtcN7) to chat more!

**Comment by yuroitaki** [comment]
Closing this as the discussion has moved to https://discord.com/channels/974410303255232542/1244750016577540136
