### ISSUE TITLE
Add CI job to run expensive integration tests

### ISSUE THREAD

**Issue by sinui0** [tlsnotary/tlsn#500]
Some integration tests, such as in `tls-mpc` are expensive so they are marked `ignore`, but these still need to be run in CI.

**Comment by heeckhau** [comment]
@sinui0 Do you want an **extra CI step** to run all ignored tests?
```
cargo test -- --ignored
```
, we can also include the ignored tests when we run the other tests:
```
cargo test -- --include-ignored
```

We could also introduce a `expensive_tests` feature, if we need to run only a few specific tests and ignore other tests.

**Comment by yuroitaki** [comment]
@sinui0 seems like this has been addressed by https://github.com/tlsnotary/tlsn/pull/537?
