### ISSUE TITLE
Fix interactive example

### ISSUE THREAD

**Issue by yuroitaki** [tlsnotary/tlsn#551]
The interactive [example](https://github.com/tlsnotary/tlsn/blob/dev/crates/examples/interactive/interactive.rs) is broken due to the use of a deprecated [endpoint](https://github.com/tlsnotary/tlsn/blob/dev/crates/examples/interactive/interactive.rs#L19) of the hosted notary server.

Replace the endpoint with a different endpoint using a different domain as the hosted notary server only has versioned endpoints now (which will always be deprecated in the future since we only maintain the latest 3 versions). This also means that the verification logic in the code has to be changed.

**Comment by heeckhau** [comment]
@yuroitaki Let's replace this with another TLS-server, using the notary server here is too confusing.
Let's use <https://example.com/> instead

**Comment by heeckhau** [comment]
Fixed in #552
