### ISSUE TITLE
bug: cannot serialize Attestation and Secrets from NotarizationOutputs

### ISSUE THREAD

**Issue by 0xtsukino** [tlsnotary/tlsn#598]
https://github.com/tlsnotary/tlsn/blob/dev/crates/wasm/src/prover/mod.rs#L138-L141

For some reason a json object is returned here instead of a serializable class

![Screenshot 2024-09-20 at 4 15 24 PM](https://github.com/user-attachments/assets/178bee4c-1ebf-4f65-ad42-5358df9db45a)

**Comment by heeckhau** [comment]
Are you sure it is json? [tsify](https://github.com/madonoharu/tsify) did create an interface `NotarizationOutput` automatically:
https://github.com/tlsnotary/tlsn-js/blob/cdd70e365e14bc12eec9cb5bbc68563ae5b83f34/wasm/pkg/tlsn_wasm.d.ts#L85 ?
