### ISSUE TITLE
Support reading config values from CLI for notary-server

### ISSUE THREAD

**Issue by yuroitaki** [tlsnotary/tlsn#604]
Support reading some of the frequently used/changed values in the config [file](https://github.com/tlsnotary/tlsn/blob/dev/crates/notary/server/config/config.yaml) from CLI, e.g.
- port
- tls.enabled
- logging.level

This can be done either via CLI parser lib like `StructOpt` or environment variable. Then something like [config-rs](https://docs.rs/config/latest/config/) can be used to combine these configs from different sources.

**Comment by maceip** [comment]
🚀

**Comment by yuroitaki** [comment]
Addressed by https://github.com/tlsnotary/tlsn/pull/605.
